server:
  port: 2382
spring:
  datasource:
    url: jdbc:mysql://8.219.183.208:8999/marketonline
    username: fary
    password: 85549060@fary
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    thymeleaf:
      cache: false
    hibernate:
      ddl-auto: update
  application:
    name: catalogservice
feign:
  client:
    config:
      default:
        loggerLevel: FULL
  httpclient:
    enable: true
    max-connections: 200
    max-connections-per-route: 50
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8111/eureka
logging:
  level:
    com:
      springcloud:
        service: debug

