spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://104.168.141.139:3306/bilibili
    username: fary
    password: 85549060@fary
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-service
server:
   port: 8080
mybatis:
 mapper-locations: classpath:mapper/*.xml
 type-aliases-package: com.bilibili.user.dao
eureka:
  instance:
    hostname: faryhuo.online
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://faryhuo.online:8111/eureka/
app:
  swagger:
    enable: true