spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://8.219.183.208:3306/bilibili
    username: fary
    password: 85549060@fary
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: following-service
server:
   port: 8081
mybatis:
 mapper-locations: classpath:mapper/*.xml
 #type-aliases-package: com.bilibili.follow.dao
feign:
  client:
    config:
      default:
        loggerLevel: FULL
  httpclient:
    enable: true
    max-connections: 200
    max-connections-per-route: 50
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8111/eureka
logging:
  level:
    com:
      bilibili: debug
app:
  swagger:
    enable: true