server:
  port: 2182
spring:
  application:
    name: orderservice
feign:
  client:
    config:
      default:
        loggerLevel: FULL
  httpclient:
    enable: true
    max-connections: 200
    max-connections-per-route: 50



