spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://8.219.183.208:8999/marketonline
    username: fary
    password: 85549060@fary
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-service
server:
   port: 8080
mybatis:
 mapper-locations: classpath:mapper/*.xml
 type-aliases-package: com.bilibili.user.dao
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8111/eureka
app:
  swagger:
    enable: true